name: ot_scintegration_env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_gnu
  - argon2-cffi=20.1.0=py38h27cfd23_1
  - arpack=3.7.0=hc6cf775_1
  - async_generator=1.10=pyhd3eb1b0_0
  - attrs=21.2.0=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - blas=1.0=mkl
  - bleach=3.3.0=pyhd3eb1b0_0
  - blosc=1.21.0=h8c45485_0
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2021.9.30=h06a4308_1
  - certifi=2021.5.30=py38h06a4308_0
  - cffi=1.14.5=py38h261ae71_0
  - cudatoolkit=10.2.89=hfd86e86_1
  - cycler=0.10.0=py38_0
  - dbus=1.13.18=hb2f20db_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - entrypoints=0.3=py38_0
  - expat=2.3.0=h2531618_2
  - ffmpeg=4.3=hf484d3e_0
  - fontconfig=2.13.1=h6c09931_0
  - freetype=2.10.4=h5ab3b9f_0
  - glib=2.68.1=h36276a3_0
  - glpk=4.65=h9202a9a_1004
  - gmp=6.2.1=h58526e2_0
  - gnutls=3.6.15=he1e5248_0
  - gst-plugins-base=1.14.0=h8213a91_2
  - gstreamer=1.14.0=h28cd5cc_2
  - hdf5=1.10.4=hb1b8bf9_0
  - icu=58.2=he6710b0_3
  - igraph=0.9.2=ha184e22_0
  - importlib-metadata=3.10.0=py38h06a4308_0
  - importlib_metadata=3.10.0=hd3eb1b0_0
  - intel-openmp=2021.2.0=h06a4308_610
  - ipykernel=5.3.4=py38h5ca1d4c_0
  - ipython=7.22.0=py38hb070fc8_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - jedi=0.17.0=py38_0
  - jinja2=2.11.3=pyhd3eb1b0_0
  - joblib=1.0.1=pyhd3eb1b0_0
  - jpeg=9b=h024ee3a_2
  - jsonschema=3.2.0=py_2
  - jupyter_client=6.1.12=pyhd3eb1b0_0
  - jupyter_core=4.7.1=py38h06a4308_0
  - jupyterlab_pygments=0.1.2=py_0
  - kiwisolver=1.3.1=py38h2531618_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - leidenalg=0.8.4=py38h709712a_0
  - libblas=3.9.0=9_mkl
  - libcblas=3.9.0=9_mkl
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.3.0=h2828fa1_19
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libgomp=9.3.0=h2828fa1_19
  - libiconv=1.15=h63c8f33_5
  - libidn2=2.3.0=h27cfd23_0
  - liblapack=3.9.0=9_mkl
  - libllvm10=10.0.1=hbcb73fb_5
  - libpng=1.6.37=hbc83047_0
  - libsodium=1.0.18=h7b6447c_0
  - libstdcxx-ng=9.3.0=h6de172a_19
  - libtasn1=4.16.0=h27cfd23_0
  - libtiff=4.2.0=h85742a9_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.0.3=h1bed415_2
  - libuv=1.40.0=h7b6447c_0
  - libwebp-base=1.2.0=h27cfd23_0
  - libxcb=1.14=h7b6447c_0
  - libxml2=2.9.10=hb55368b_3
  - llvmlite=0.36.0=py38h612dafd_4
  - lz4-c=1.9.3=h2531618_0
  - lzo=2.10=h7b6447c_2
  - markupsafe=1.1.1=py38h7b6447c_0
  - matplotlib=3.3.4=py38h06a4308_0
  - matplotlib-base=3.3.4=py38h62a2d02_0
  - metis=5.1.0=h58526e2_1006
  - mistune=0.8.4=py38h7b6447c_1000
  - mkl=2021.2.0=h06a4308_296
  - mkl-service=2.3.0=py38h27cfd23_1
  - mkl_fft=1.3.0=py38h42c9631_2
  - mkl_random=1.2.1=py38ha9443f7_2
  - mock=4.0.3=pyhd3eb1b0_0
  - nb_conda=2.2.1=py38_1
  - nb_conda_kernels=2.3.1=py38h06a4308_0
  - nbclient=0.5.3=pyhd3eb1b0_0
  - nbconvert=6.0.7=py38_0
  - nbformat=5.1.3=pyhd3eb1b0_0
  - ncurses=6.2=he6710b0_1
  - nest-asyncio=1.5.1=pyhd3eb1b0_0
  - nettle=3.7.2=hbbd107a_1
  - ninja=1.10.2=hff7bd54_1
  - notebook=6.3.0=py38h06a4308_0
  - numba=0.53.1=py38ha9443f7_0
  - numexpr=2.7.3=py38h22e1b3c_1
  - numpy=1.20.1=py38h93e21f0_0
  - numpy-base=1.20.1=py38h7d8b39e_0
  - olefile=0.46=py_0
  - openh264=2.1.0=hd408876_0
  - openssl=1.1.1l=h7f8727e_0
  - packaging=20.9=pyhd3eb1b0_0
  - pandas=1.2.4=py38h2531618_0
  - pandoc=2.12=h06a4308_0
  - pandocfilters=1.4.3=py38h06a4308_1
  - parso=0.8.2=pyhd3eb1b0_0
  - patsy=0.5.1=py38_0
  - pcre=8.44=he6710b0_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=8.2.0=py38he98fc37_0
  - pip=21.0.1=py38h06a4308_0
  - prometheus_client=0.10.1=pyhd3eb1b0_0
  - prompt-toolkit=3.0.17=pyh06a4308_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pycparser=2.20=py_2
  - pygments=2.8.1=pyhd3eb1b0_0
  - pyparsing=2.4.7=pyhd3eb1b0_0
  - pyqt=5.9.2=py38h05f1152_4
  - pyrsistent=0.17.3=py38h7b6447c_0
  - pytables=3.6.1=py38h9fd0a39_0
  - python=3.8.8=hdb3f193_5
  - python-dateutil=2.8.1=pyhd3eb1b0_0
  - python-igraph=0.9.1=py38h2af5540_0
  - python_abi=3.8=1_cp38
  - pytorch=1.8.1=py3.8_cuda10.2_cudnn7.6.5_0
  - pytz=2021.1=pyhd3eb1b0_0
  - pyzmq=20.0.0=py38h2531618_1
  - qt=5.9.7=h5867ecd_1
  - readline=8.1=h27cfd23_0
  - scikit-learn=0.24.1=py38ha9443f7_0
  - scipy=1.6.2=py38had2a1c9_1
  - seaborn=0.11.1=pyhd3eb1b0_0
  - send2trash=1.5.0=pyhd3eb1b0_1
  - setuptools=52.0.0=py38h06a4308_0
  - sip=4.19.13=py38he6710b0_0
  - six=1.15.0=py38h06a4308_0
  - sqlite=3.35.4=hdfb4753_0
  - statsmodels=0.12.2=py38h27cfd23_0
  - suitesparse=5.7.2=h7a0d4b7_0
  - tbb=2020.3=hfd86e86_0
  - terminado=0.9.4=py38h06a4308_0
  - testpath=0.4.4=pyhd3eb1b0_0
  - texttable=1.6.3=pyh9f0ad1d_0
  - threadpoolctl=2.1.0=pyh5ca1d4c_0
  - tk=8.6.10=hbc83047_0
  - torchaudio=0.8.1=py38
  - torchvision=0.9.1=py38_cu102
  - tornado=6.1=py38h27cfd23_0
  - traitlets=5.0.5=pyhd3eb1b0_0
  - typing_extensions=3.7.4.3=pyha847dfd_0
  - wcwidth=0.2.5=py_0
  - webencodings=0.5.1=py38_1
  - wheel=0.36.2=pyhd3eb1b0_0
  - xz=5.2.5=h7b6447c_0
  - zeromq=4.3.4=h2531618_0
  - zipp=3.4.1=pyhd3eb1b0_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.5=h9ceee32_0
  - pip:
    - absl-py==0.12.0
    - aiohttp==3.7.4.post0
    - anndata==0.7.6
    - async-timeout==3.0.1
    - cachetools==4.2.2
    - chardet==4.0.0
    - click==8.0.1
    - decorator==4.4.2
    - fsspec==2021.5.0
    - future==0.18.2
    - get-version==2.2
    - google-auth==1.30.0
    - google-auth-oauthlib==0.4.4
    - grpcio==1.37.1
    - h5py==3.2.1
    - idna==2.10
    - itsdangerous==2.0.1
    - legacy-api-wrap==1.2
    - loompy==3.0.6
    - markdown==3.3.4
    - multidict==5.1.0
    - muon==0.1.0
    - natsort==7.1.1
    - networkx==2.5.1
    - nimfa==1.4.0
    - nn-fac==0.1.2
    - nose==1.3.7
    - numpy-groupies==0.9.13
    - oauthlib==3.1.0
    - opt-einsum==3.3.0
    - protobuf==3.17.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pybiomart==0.2.0
    - pydeprecate==0.3.0
    - pytorch-lightning==1.3.1
    - pyyaml==5.4.1
    - requests==2.25.1
    - requests-cache==0.6.3
    - requests-oauthlib==1.3.0
    - rpy2==3.4.5
    - rsa==4.7.2
    - scanpy==1.7.2
    - scikit-misc==0.1.4
    - scmiot==0.0.1
    - sinfo==0.3.4
    - sklearn==0.0
    - stdlib-list==0.8.0
    - tensorboard==2.4.1
    - tensorboard-plugin-wit==1.8.0
    - tensorly==0.6.0
    - torchmetrics==0.3.2
    - tqdm==4.60.0
    - tzlocal==2.1
    - url-normalize==1.4.3
    - urllib3==1.26.4
    - werkzeug==2.0.0
    - xlrd==1.2.0
    - yarl==1.6.3
prefix: /users/csb/huizing/anaconda3/envs/ot_scintegration_env
